### ISSUE TITLE
WatchLeases does not send any update when the lease file gets empty

### ISSUE THREAD

**Issue by f18m** [b0ch3nski/go-dnsmasq-utils#3]
I noticed that the library has some code like:

```
		leases, errRead := ReadLeases(leaseFile)
		if len(leases) > 0 {
			output <- leases
		}
```

I think we should use as if condition "len(leases) >= 0" because it's legal to get the lease file empty (all leases expired)...

**Comment by b0ch3nski** [comment]
@f18m I've redo some logic around DHCP leases (and tests too) - please try [v0.1.2](https://github.com/b0ch3nski/go-dnsmasq-utils/releases/tag/v0.1.2) :slightly_smiling_face:
